FROM node:20-alpine AS build

WORKDIR /app
RUN apk add --no-cache tzdata
COPY app/package*.json ./
RUN npm install
COPY app .
RUN npm run build

FROM nginx:alpine
RUN apk add --no-cache tzdata
COPY --from=build /app/dist /usr/share/nginx/html
