from .usuarios.User import User
from .usuarios.Cinturon import Cinturon
from .usuarios.Alumno import Alumno
from .configuracion.Temporada import Temporada
from .configuracion.TarifaMensual import TarifaMensual
from .configuracion.TipoLicencia import TipoLicencia
from .pagos.LicenciaAlumno import LicenciaAlumno
from .pagos.InscripcionMensual import InscripcionMensual
from .pagos.PagoMensualidad import PagoMensualidad
from .eventos.Evento import Evento
from .eventos.Participacion import Participacion
from .eventos.ResultadoCompeticion import ResultadoCompeticion
from .eventos.Asistencia import Asistencia
